### ISSUE TITLE
Is any validation against EASY-BagIt specs done?

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-deposit#15]
We check the bags against the BagIt specs, but EASY-BagIt adds some specs. Do we check those?

**Comment by janvanmansum** [comment]
We could move this check out of `easy-deposit` and into post-submission processing. That way `easy-deposit` could just accept BagIt as a format. Not providing the necessary metadata could be regarded as a ground to reject the deposit on the same level as submitting a deposit containing a virus or one that violates some other submission agreement rules.

@GeorgiKhomeriki , any thoughts?

**Comment by GeorgiKhomeriki** [comment]
Yes, we could do that. Most of the checks are done during the post-process anyway. And it will relieve easy-deposit from most of the "hard work". But do you want to check whether the package is in actual BagIt format in easy-deposit? If so, how should we do that?
