### ISSUE TITLE
JGit's `describe` does not return latest tag

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-deposit#29]
Related to #27 . On the command line `git describe` seems to print the most recently added tag label, which made it look like a good way to implement retrieving the state. As we've seen in #27 this will not work for more complex use cases. Now it also turns out not to work for the simple use case, because JGit returns the earliers tag (or maybe there is no inherent order?). 

So, we'll need a way to list all the tags and find out which one is the most recent and use that one.

**Comment by janvanmansum** [comment]
Opted for implementing the deposit's state outside git, in a file called `state.properties` in the root of the deposit directory. I will describe this in the README. An added benefit of this is that we can better record the state history in the git-enabled version. Each time the state changes we could commit the new state.properties file and tag the new commit. JGit's  `describe` bug isn't a problem anymore either.

**Comment by GeorgiKhomeriki** [comment]
Sounds good. I've noticed on the test server that there are certain deposits (e.g. 1443126437167) that have a modified state.properties but it hasn't been committed to the repo yet. The diff shows that the state was changed from SUBMITTED to ARCHIVED. Shouldn't this update have been committed and tagged as well?
