### ISSUE TITLE
Store password as hash instead of as clear text in one-user set-up

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-deposit#38]
@DANS-KNAW/easy 
EASY-921

Storing passwords in clear text is an anti-pattern. In the single-user set-up it is still done this way. Instead of the password itself store a hash. Some research in how to this properly may be in order, e.g. https://crackstation.net/hashing-security.htm

**Comment by jo-pol** [comment]
Can this one be closed now that #50 is merged?

**Comment by janvanmansum** [comment]
Implemented in #50
